name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run zip && npm run zip:firefox

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .output/carmentis-wallet-extension*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .output/carmentis-wallet-extension*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: .output/carmentis-wallet-extension*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}