# .github/workflows/publish-release.yml
name: Publish release
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
      - name: Build releases
        run: make zip-chrome zip-firefox

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          assets:
            - path: .output/carmentis-wallet-extension*